### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/asm-parser#22]
Hi @mattgodbolt told me about you using CTRE here, I read the code and noticed this:

https://github.com/compiler-explorer/asm-parser/blob/74f51e4f21810931531a80f17a7a6e00fb56a894/src/utils/regexwrappers.cpp#L20-L21

You can use `.to_number<T>()` on capture group :)

**Comment by hanickadot** [comment]
`match.to_number()` (int is default)

**Comment by mattgodbolt** [comment]
That's awesome! Thanks @hanickadot !
