### ISSUE TITLE
Use latest CTRE instead of v2.8.2

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/asm-parser#3]
But latest is not in Conan.io

**Comment by axalon900** [comment]
Hi, I'm the one who uploaded the original CTRE recipe to conan-center. Sorry about that, I didn't realize CTRE made so many releases over the past few months. I made a PR over at the [conan-center-index](https://github.com/conan-io/conan-center-index) project backfilling everything between 2.8.2 and 3.2, and hopefully that should be merged in in the coming days.

If you want/need packages in the future, feel free to open an issue requesting a new package or updated versions for an existing package. All updates are currently initiated manually via PR so it's easy for stuff to fall through the cracks sometimes.

**Comment by partouf** [comment]
OH thanks! I have no idea how all the conan sources work, its pretty much black magic to me. Will make a mental note of this

**Comment by axalon900** [comment]
Check conan. ;)

**Comment by partouf** [comment]
Thanks! Set it up and it works. I noticed I had already used a different conan source to use 3.2, but swapped it back to use conan.io again.
Might swap to bleeding edge main at one point, but this is fine for now.
