### ISSUE TITLE
Unable to build / docs for setting up for build (on Ubuntu 24)

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/asm-parser#38]
Are there some instructions for setting up a build? Would be cool to debug this. I tried the `setup.sh` (even though it goes against my personal dislike of `sudo` installing things...) but that failed too.

I tried with a manual `cmake` setup too and that failed with:
```
$ cmake ..
-- Conan: checking conan executable
-- Conan: Found program /home/matthew/.ozy/bin/conan
CMake Error at build/conan.cmake:806 (message):
  Conan --version failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:23 (conan_check)

```

Is there perhaps a version of particualr conan I should use?

**Comment by mattgodbolt** [comment]
Maybe #36  is meant to fix this?

**Comment by mattgodbolt** [comment]
I installed conan 2.1.0; it doesn't work with the setup.sh:
```
bollo:~/d/c/a/build (main|✔) $ conan profile update settings.compiler.libcxx=libstdc++11 default
usage: conan profile [-h] [-v [V]] [-cc CORE_CONF] {detect,list,path,show} ...
conan profile: error: argument subcommand: invalid choice: 'update' (choose from 'detect', 'list', 'path', 'show')
```

but it got further...

...
```
======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /home/matthew/dev/ce/asm-parser/build
ERROR: Invalid generator 'cmake'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps, MakeDeps, SConsDeps
CMake Error at build/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:25 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
```
but still failed.

**Comment by mattgodbolt** [comment]
I found the change that hardcodes the build to conan 1.59.0 and am trying that...

**Comment by partouf** [comment]
`python3 -m pip install conan==1.59`

probably need to move/backup your cachedir (`~/.conan`) before you do that

**Comment by mattgodbolt** [comment]
Now I get:
```
ERROR: Invalid setting '13' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '8.5', '9', '9.1', '9.2', '9.3', '9.4', '9.5', '10', '10.1', '10.2', '10.3', '10.4', '11', '11.1', '11.2', '11.3', '12', '12.1', '12.2']
```

**Comment by mattgodbolt** [comment]
I deleted my cache dir and made no difference. I'll try an older GCC now

**Comment by partouf** [comment]
`~/.conan/settings.yml` controls the versions you can use, you can just expand that

**Comment by mattgodbolt** [comment]
I hate all the editing of global things... but installing gcc 12.1 and pointing at conan 1.59.0 and the gcc 12.2 I confirm lets me `cmake` :D  and now I'm trying to build ... and it's taking a looooooooooooong while... so hopefully it's working...

**Comment by mattgodbolt** [comment]
a debug build completed! yay! took 1.9m :)

**Comment by partouf** [comment]
the long build is probably because of ctre regexes, but if you build incrementally after its built once, it should be much faster
